--- #disabling selinux
-  hosts: local
   remote_user: root
   gather_facts: yes
   tasks:
   -  name: stop and disable firewalld
      systemd:
        name: firewalld
        enabled: False
        state: stopped
      ignore_errors: yes
   -  name: disable selinux
      selinux:
        state: disabled
      notify: reboot
   handlers:
   -  name: reboot
      shell: shutdown -r now
