--- #Exercise: Playbooks - Lookup
-  hosts: centos
   gather_facts: yes
   vars:
     home_directory: "{{ lookup('dig', 'sidev1704.sandbox.factset.com.') }}"
   tasks:
     - debug:
         msg: "USER NAME IS  {{ home_directory }}"
  
