---
- hosts: all
  become: yes
  tasks:
    - name: update packages
      yum:
        name: "*"
        state: latest
      register: update_status
      notify: reboot

    - name: log status
      copy:
        content: "{{ update_status }}"
        dest: /root/linux{{ ansible_host}}_updates.log
  handlers:
    - name: reboot
      shell: shutdown -r now
