--- # Playbooks - Run Once
-  hosts: all
   gather_facts: yes 
   tasks:
   -  name: Run the uptime command on all hosts and log it
      raw: /usr/bin/uptime >> /root/uptime.log
   -  name: List the /var directory and log it
      raw: ls -al /var >> /root/dir.list
      run_once: true
