-  hosts: all
   remote_user: root
   vars:
     from1: "camelot"
   vars_prompt:
     - name: pkg
       prompt: "what is your package?"
       default: telnet
   tasks:
   - name: Install desired package
     yum:
     name: "{{ pkg }}"
     state: present
